(defun pos (x) (if x (if (sub 1 x) 1 0) 0))
(defun fib (x) (if (pos x) (add (fib (sub x 1)) (fib (sub x 2))) 1))
(defun range (n) (if n (cons n (range (sub n 1))) 0))
(defun sum (L) (if L (add (car L) (sum (cdr L))) 0))
(defun printmap (L) (if L (cons (print (car L)) (printmap (cdr L))) 0))
(defun fibmap (L) (if L (cons (fib (car L)) (fibmap (cdr L))) 0))
(defun reverse_impl (L acc) (if L (reverse_impl (cdr L) (cons (car L) acc)) acc))
(defun reverse (L) (reverse_impl L 0))
(defun main () (print (fib 7)))
