name: test

on:
  pull_request:
  push:
    branches: master

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Test examples
      run: |
        make test SRC=examples/ffi.lisp
        make test SRC=examples/primes.lisp
        make test SRC=examples/sierpenski.lisp
        make test SRC=examples/parser5.lisp
        make test SRC=examples/calculus.lisp
