name: test

on:
  pull_request:
  push:
    branches: master

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend:
          - ctest
          - test
          - jstest

    steps:
    - uses: actions/checkout@v5
    - name: Test examples
      run: |
        make ${{ matrix.backend }}  SRC=examples/ffi.lisp
        make ${{ matrix.backend }} SRC=examples/primes.lisp
        make ${{ matrix.backend }} SRC=examples/sierpenski.lisp
        make ${{ matrix.backend }} SRC=examples/parser7.lisp
        make ${{ matrix.backend }} SRC=examples/calculus.lisp
