name: test

on:
  pull_request:
  push:
    branches: master

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Test examples
      run: |
        make test SRC=examples/ffi.lisp
        make test SRC=examples/primes.lisp
        make test SRC=examples/sierpenski.lisp
        make test SRC=examples/parser5.lisp
        make test SRC=examples/calculus.lisp
